// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeWorker() (*Worker, error) {
	logger := NewLogger()
	dbConnection, err := NewDBConnection(logger)
	if err != nil {
		return nil, err
	}
	worker, err := NewWorker(logger, dbConnection)
	if err != nil {
		return nil, err
	}
	return worker, nil
}
