// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeWorker(config Config) (*Worker, func(), error) {
	logger := LoggerProvider(config)
	dbConnection, cleanup, err := DBConnectionProvider(config, logger)
	if err != nil {
		return nil, nil, err
	}
	worker, err := NewWorker(logger, dbConnection)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return worker, func() {
		cleanup()
	}, nil
}

// wire.go:

// Нам придется написать кастомные провайдеры чтобы достать параметры из конфига
func LoggerProvider(config Config) *Logger {
	logger := NewLogger(config.LogLevel)

	return logger
}

func DBConnectionProvider(config Config, logger *Logger) (*DBConnection, func(), error) {
	conn, err := NewDBConnection(config.DBHost, logger)

	cleanup := func() {
		conn.Close()
	}
	return conn, cleanup, err
}
