// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// Входные параметры инжектятся автоматически
func InitializeWorker(host string) (*Worker, func(), error) {
	logger := NewLogger()
	dbConnection, cleanup, err := DBConnectionProvider(host, logger)
	if err != nil {
		return nil, nil, err
	}
	worker, err := NewWorker(logger, dbConnection)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return worker, func() {
		cleanup()
	}, nil
}

// wire.go:

func DBConnectionProvider(host string, logger *Logger) (*DBConnection, func(), error) {
	conn, err := NewDBConnection(host, logger)

	cleanup := func() {
		conn.Close()
	}
	return conn, cleanup, err
}
