// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// Функция - инжектор
func InitializeWorker() *Worker {
	logger := NewLogger()
	dbConnection := NewDBConnection(logger)
	worker := NewWorker(dbConnection)
	return worker
}
