// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeWorker(config AppConfig) (*Worker, func(), error) {
	loggerConfig := config.LoggerConfig
	logger := NewLogger(loggerConfig)
	dbConfig := config.DBConfig
	dbConnection, cleanup, err := DBConnectionProvider(dbConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	worker, err := NewWorker(logger, dbConnection)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return worker, func() {
		cleanup()
	}, nil
}

// wire.go:

func DBConnectionProvider(config DBConfig, logger *Logger) (*DBConnection, func(), error) {
	conn, err := NewDBConnection(config, logger)

	cleanup := func() {
		conn.Close()
	}
	return conn, cleanup, err
}
